lib/ndm_web/router.ex
defmodule NdmWeb.Router do
  use NdmWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :require_login do
    plug NdmWeb.Plugs.RequireLogin
  end

  scope "/", NdmWeb do
    pipe_through :browser

    resources "/", SessionController, only: [:new, :create]

    resources "/", PageController, only: [:index]

    delete "/logout", SessionController, :delete
  end

  scope "/", NdmWeb do
    pipe_through [:browser, :require_login]

    # resources "/", PageController, only: [:index]

    resources "/dailies", DailiesController, only: [:index, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", NdmWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: NdmWeb.Telemetry
    end
  end
end

lib/ndm_web/views/layout_view.ex
defmodule NdmWeb.LayoutView do
  use NdmWeb, :view

  def active_class(conn, path) do
    current_path = Path.join(["/" | conn.path_info])

    if path == current_path do
      "is-active"
    else
      nil
    end
  end

  def active_link(text, conn, opts) do
    class = [opts[:class], active_class(conn, opts[:to])] |> Enum.filter(& &1) |> Enum.join(" ")
    opts = opts |> Keyword.put(:class, class) |> Keyword.put(:to, opts[:to])
    link(text, opts)
  end
end

lib/ndm_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Ndm · Neopets Daily Manager</title>
    <script src="https://kit.fontawesome.com/ec995100e0.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <main role="main">
    <div class="section">
      <div class="columns">
      <%= render "nav.html", conn: @conn %>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
      </div>
    </div>
    </main>
  </body>
</html>

lib/ndm_web/templates/layout/nav.html.eex
<aside class="column is-2">
  <nav class="menu">
    <p class="menu-label">General</p>
    <ul class="menu-list">
      <li><%= active_link "Dashboard", @conn, to: Routes.page_path(@conn, :index)%></li>
    </ul>
    <p class="menu-label">Tools</p>
    <ul class="menu-list">
      <li><%= link "Daily Manager", to: Routes.dailies_path(@conn, :index), class: active_class(@conn, Routes.dailies_path(@conn, :index))%></li>
      <li><a>Stock Broker</a></li>
      <li><a>Shop Pricer</a></li>
      <li><a>Page Crawler</a></li>
    </ul>
    <p class="menu-label">Account</p>
    <ul class="menu-list">
      <li><a>Settings</a></li>
      <li><a>Log Out</a></li>
    </ul>
  </nav>
</aside>